# -*- coding: utf-8 -*-
"""Numpy Array Creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5F9FAPk9XGEkbamKl8pyz4wbDOx1dyg
"""

import numpy as np

"""# **Array Creation in Numpy**

## 1) np.array([List])
"""

#Using np.array([List]) --> 1D
m = np.array([8,5,4,3,5])
m

# #Using np.array([List]) --> 2D
n = np.array([[7,8,9,4],[5,6,1,2]])
n

# #Using np.array([List]) --> 3D
o = np.array([[7,8,9,4],[5,6,1,2],[10,11,12,13]])
o

"""## 2) np.arange(included, excluded, step)"""

m = np.arange(0,10)
m

n = np.arange(0,10,2)
n

"""# You can use .reshape(row, col)"""

arr = np.arange(1,9).reshape(4,2)
arr

"""## 3) np.zeros(size) and np.ones(size)"""

#1D
A = np.zeros(5, dtype = np.int8)
A

#2D
A = np.zeros((5,5), dtype = np.int8)
A

#3D
A = np.ones((2,3,3), dtype = np.int8)
A

"""## 4) np.linspace(starting range, ending range, no of element need)"""

B = np.linspace(-10, 10, 5, dtype=np.int8)
B

"""## 5) np.random.random(tuple(row,col))"""

#1D
C = np.random.random(5)
C

#2D
C = np.random.random((5,3))
C

#3D
D = np.random.random((2,3,2))
D

"""## 6) np.identity(size)"""

E = np,np.identity(5)
E

